part of '../loom_communities_app_shell.dart';

const Map<String, LoomExperienceDefinition> _experienceByExtensionId = {
  'ext_garden_club': LoomExperienceDefinition(
    extensionId: 'ext_garden_club',
    displayName: 'Garden Club',
    tagline: 'Coordinate garden events and plant exchange requests.',
    accentColor: 0xff3a7d44,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'garden-event-rsvp',
        title: 'Garden event RSVP',
        entryText: 'Spring planting workshop is open for member RSVP.',
        actionText:
            'RSVP to the spring planting workshop through the Garden Club UI.',
        resultText: 'RSVP recorded for Spring planting workshop.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'plant-exchange-submission',
        title: 'Plant exchange submission',
        entryText: 'Members can offer seedlings and request exchange matches.',
        actionText: 'Submit a basil seedling offer to the plant exchange.',
        resultText: 'Plant exchange record created for basil seedlings.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'garden-tool-loan',
        title: 'Garden tool loan',
        entryText: 'Shared garden tools are available to borrow or queue for.',
        actionText: 'Borrow the broadfork and manage the loan queue.',
        resultText: 'Garden tool loan state updated.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'garden-volunteer-shift',
        title: 'Garden volunteer shift',
        entryText: 'Compost turning shift has open volunteer slots.',
        actionText: 'Sign up for the compost turning volunteer shift.',
        resultText: 'Volunteer shift signup updated.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'garden-export-custom-schemas',
        title: 'Garden export custom schemas',
        entryText: 'Garden event and plant exchange schemas are exportable.',
        actionText: 'Generate Garden Club export evidence for custom schemas.',
        resultText: 'Export includes garden_event and plant_exchange schemas.',
      ),
    ],
  ),
  'ext_book_club': LoomExperienceDefinition(
    extensionId: 'ext_book_club',
    displayName: 'Neighborhood Book Club',
    tagline: 'Nominate, vote, meet, discuss, and digest club selections.',
    accentColor: 0xff246b62,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'book-nomination',
        title: 'Book nomination',
        entryText: 'Nomination form is ready for the next monthly selection.',
        actionText: 'Submit Parable of the Sower as the member nomination.',
        resultText: 'Nomination saved for Parable of the Sower.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'book-vote',
        title: 'Book vote',
        entryText: 'Monthly poll accepts member votes.',
        actionText: 'Record one vote for Parable of the Sower.',
        resultText: 'Vote count updated for Parable of the Sower.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'book-meeting-rsvp',
        title: 'Meeting event RSVP',
        entryText: 'Discussion event has available capacity.',
        actionText: 'RSVP to Discuss Parable of the Sower.',
        resultText: 'Meeting RSVP ticket issued.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'book-discussion-message',
        title: 'Discussion message',
        entryText: 'Book discussion thread is open.',
        actionText: 'Post a discussion-prep message to the thread.',
        resultText: 'Discussion message posted to book_discussion.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'book-selection-publish',
        title: 'Selected-book publishing',
        entryText: 'Owner can publish the monthly winning selection.',
        actionText: 'Publish January selection for Parable of the Sower.',
        resultText: 'Selected-book announcement published.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'book-search-ai-digest',
        title: 'Search, AI answer, and digest',
        entryText: 'Public selection content is indexable for cited summaries.',
        actionText: 'Generate a cited digest for the Parable selection.',
        resultText: 'Digest generated with citation evidence.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'book-export-metadata',
        title: 'Book export metadata',
        entryText: 'Nomination and vote schemas are exportable.',
        actionText: 'Create export metadata for Book Club custom data.',
        resultText: 'Export includes book_nomination and book_vote schemas.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'book-library-item',
        title: 'Shared library item',
        entryText:
            'Members can borrow, queue for, return, and claim shared items.',
        actionText: 'Borrow and manage the club library item.',
        resultText: 'Shared library custody state updated.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'book-reading-material',
        title: 'Reading material',
        entryText: 'Current reading guides and author links are available.',
        actionText: 'Open the current reading guide.',
        resultText: 'Reading material opened.',
      ),
    ],
  ),
  'ext_youth_soccer': LoomExperienceDefinition(
    extensionId: 'ext_youth_soccer',
    displayName: 'Riverside Youth Soccer',
    tagline: 'Manage guardian flows, teams, privacy, payments, and schedules.',
    accentColor: 0xff1f7a5c,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'soccer-guardian-join-approval',
        title: 'Guardian join and approval',
        entryText: 'Guardian membership request is waiting for approval.',
        actionText: 'Approve the guardian membership request.',
        resultText: 'Guardian membership is active.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'soccer-team-roster',
        title: 'Team and roster view',
        entryText: 'U10 Falcons team space is ready for roster display.',
        actionText: 'Open the U10 Falcons team roster.',
        resultText: 'Roster view displays U10 Falcons.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'soccer-minor-redaction',
        title: 'Protected minor-data redaction',
        entryText: 'Minor birthdate is stored behind protected permissions.',
        actionText: 'Read protected minor data through permission-gated UI.',
        resultText: 'Minor birthdate renders as redacted value 2***.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'soccer-registration-payment',
        title: 'Registration payment',
        entryText: 'Registration checkout is owned by Loom payment surface.',
        actionText: 'Pay the 125.00 USD registration dues.',
        resultText: 'Registration payment receipt recorded.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'soccer-practice-schedule',
        title: 'Practice schedule',
        entryText: 'Saturday practice event has capacity for the team.',
        actionText: 'Publish Saturday practice to the schedule.',
        resultText: 'Practice event scheduled with capacity 18.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'soccer-reminder-notification',
        title: 'Reminder notification',
        entryText: 'Practice reminder can be delivered to guardians.',
        actionText: 'Send Practice starts at 9 AM reminder.',
        resultText: 'Practice reminder delivered once.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'soccer-export-metadata',
        title: 'Youth soccer export metadata',
        entryText: 'Registration and roster schemas are exportable.',
        actionText: 'Generate protected export metadata for youth soccer.',
        resultText: 'Export metadata includes registration and roster schemas.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'soccer-waiver-document',
        title: 'Waiver document library',
        entryText:
            'The current waiver is available for embedded and external review.',
        actionText: 'Open and acknowledge the current youth sports waiver.',
        resultText: 'Waiver acknowledgement is recorded with an audit trail.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'soccer-team-discussion',
        title: 'Team discussion thread',
        entryText: 'Guardian and coach messages are tied to the U10 team.',
        actionText: 'Reply to the weekend coordination thread.',
        resultText: 'Team discussion reply is recorded.',
      ),
    ],
  ),
  'ext_hoa': LoomExperienceDefinition(
    extensionId: 'ext_hoa',
    displayName: 'Cedar Commons HOA',
    tagline: 'Run dues, documents, facilities, reviews, and exports.',
    accentColor: 0xff3e6b8f,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'hoa-dues-payment',
        title: 'Dues payment',
        entryText: 'Quarterly dues checkout is ready.',
        actionText: 'Record a 450.00 USD HOA dues payment.',
        resultText: 'Dues payment receipt recorded.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'hoa-member-document',
        title: 'Member-visible document',
        entryText: 'Community Rules document is visible to members.',
        actionText: 'Open the member-visible governing document.',
        resultText: 'Community Rules document displayed.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'hoa-facility-reservation',
        title: 'Facility reservation and payment',
        entryText: 'Clubhouse Room A can be reserved with payment.',
        actionText: 'Reserve Clubhouse Room A and pay reservation fee.',
        resultText: 'Facility reservation held with payment.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'hoa-architectural-request',
        title: 'Architectural request',
        entryText: 'Fence color request is ready for board action.',
        actionText: 'Submit architectural request for committee decision.',
        resultText: 'Architectural request case opened.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'hoa-committee-decision',
        title: 'Committee decision',
        entryText: 'Committee decision step is waiting.',
        actionText: 'Approve the architectural request.',
        resultText: 'Architectural request approved.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'hoa-owner-notification',
        title: 'Owner notification',
        entryText: 'Owner notification can be delivered after decision.',
        actionText: 'Notify owner that the architectural request was approved.',
        resultText: 'Owner notification delivered.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'hoa-export-evidence',
        title: 'HOA export evidence',
        entryText: 'Documents, facilities, wallet, receipts, and cases export.',
        actionText: 'Generate HOA export coverage evidence.',
        resultText: 'Export includes HOA document and operational components.',
      ),
    ],
  ),
  'ext_mosque': LoomExperienceDefinition(
    extensionId: 'ext_mosque',
    displayName: 'Masjid Nur',
    tagline: 'Coordinate announcements, events, volunteers, giving, and care.',
    accentColor: 0xff2d6a4f,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'mosque-announcement',
        title: 'Public announcement',
        entryText: 'Ramadan community night announcement is ready.',
        actionText: 'Publish Ramadan community night announcement.',
        resultText: 'Public announcement published.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'mosque-event-rsvp',
        title: 'Community event RSVP',
        entryText: 'Community iftar event has available capacity.',
        actionText: 'RSVP to the community iftar.',
        resultText: 'Community iftar RSVP ticket issued.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'mosque-volunteer-signup',
        title: 'Volunteer signup',
        entryText: 'Iftar volunteer form protects contact details.',
        actionText: 'Submit setup shift with protected phone field.',
        resultText: 'Volunteer signup saved and phone field protected.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'mosque-donor-visibility',
        title: 'Anonymous donor visibility',
        entryText: 'Donation visibility preference is member-owned.',
        actionText: 'Set donor visibility to anonymous.',
        resultText: 'Donor visibility preference saved as anonymous.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'mosque-donation-payment',
        title: 'Donation payment and receipt',
        entryText: 'Donation checkout is available through Loom wallet.',
        actionText: 'Record a 50.00 USD donation.',
        resultText: 'Donation payment receipt recorded.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'mosque-care-request',
        title: 'Protected care request',
        entryText:
            'Care request form separates public summary and private details.',
        actionText:
            'Submit a meal-support care request with protected details.',
        resultText: 'Care request saved with protected details redacted.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'mosque-neutral-notification',
        title: 'Neutral care notification',
        entryText:
            'Care request acknowledgement avoids sensitive detail leakage.',
        actionText: 'Send neutral care-request receipt notification.',
        resultText: 'Neutral care-request notification delivered.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'mosque-search-ai-citation',
        title: 'Announcement search and AI citation',
        entryText: 'Public announcement can be searched and cited.',
        actionText: 'Ask for iftar information from indexed announcements.',
        resultText: 'AI answer includes public announcement citation.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'mosque-discussion-thread',
        title: 'Community discussion thread',
        entryText:
            'Members can discuss iftar logistics without leaking protected care details.',
        actionText: 'Reply to the iftar logistics thread.',
        resultText: 'Discussion thread updated.',
      ),
    ],
  ),
  'ext_chess_club': LoomExperienceDefinition(
    extensionId: 'ext_chess_club',
    displayName: 'Chess Club',
    tagline: 'Propose matches, record results, and keep live ladder rankings.',
    accentColor: 0xff58432f,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'chess-match-meetup',
        title: 'Match meetup',
        entryText:
            'Players can propose, negotiate, and confirm ladder matches.',
        actionText: 'Propose and confirm a Board 1 ladder match.',
        resultText: 'Ladder match confirmed on the club calendar.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'chess-match-result',
        title: 'Match result record',
        entryText: 'Players can record a result that updates rankings.',
        actionText: 'Submit the Board 1 match result.',
        resultText: 'Match result saved and rankings updated.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'chess-rankings-table',
        title: 'Live rankings table',
        entryText: 'Rankings use the table archetype with ranking emphasis.',
        actionText: 'Review the live ladder rankings.',
        resultText: 'Live rankings table displayed.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'chess-club-night',
        title: 'Club night calendar',
        entryText: 'The next ladder night has confirmed pairings.',
        actionText: 'Open the club night calendar entry.',
        resultText: 'Club night calendar entry displayed.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'chess-pairing-queue',
        title: 'Organizer pairing queue',
        entryText: 'Organizer can assign players waiting for ladder pairings.',
        actionText: 'Assign the next pairing.',
        resultText: 'Pairing queue updated.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'chess-export-package',
        title: 'Chess records export',
        entryText: 'Organizer can export match and ranking records.',
        actionText: 'Generate Chess Club export evidence.',
        resultText: 'Chess Club export package generated.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'chess-rules-documents',
        title: 'Rules documents',
        entryText: 'Organizer can open and download club rules.',
        actionText: 'Open the club rules document.',
        resultText: 'Club rules document opened.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'chess-discussion-thread',
        title: 'Pairing discussion',
        entryText: 'Players can coordinate pairings in a discussion thread.',
        actionText: 'Reply to the pairing thread.',
        resultText: 'Pairing thread updated.',
      ),
    ],
  ),
  'ext_camera_club': LoomExperienceDefinition(
    extensionId: 'ext_camera_club',
    displayName: 'Camera Club',
    tagline: 'Plan photo walks, critique work, and loan gear.',
    accentColor: 0xff465c7b,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'photo-walk-rsvp',
        title: 'Photo-walk RSVP',
        entryText: 'Downtown photo walk is accepting member RSVPs.',
        actionText: 'RSVP to the next photo walk.',
        resultText: 'Photo-walk RSVP recorded.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'critique-submission',
        title: 'Critique submission',
        entryText: 'Critique board accepts new photo submissions.',
        actionText: 'Submit a street portrait for critique.',
        resultText: 'Critique submission saved.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'gear-loan-request',
        title: 'Gear-loan request',
        entryText: 'Members can request shared gear loans.',
        actionText: 'Request the 35mm prime lens loan.',
        resultText: 'Gear-loan request created and pending response.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'camera-validation-report',
        title: 'Camera validation report',
        entryText: 'Organizer validation status is ready for review.',
        actionText: 'Mark the Camera Club package validation complete.',
        resultText: 'Camera Club validation status updated.',
      ),
    ],
  ),
  'ext_platform_social': LoomExperienceDefinition(
    extensionId: 'ext_platform_social',
    displayName: 'Member Social Space',
    tagline: 'Manage messages, connections, and sponsored-message settings.',
    accentColor: 0xff315c8a,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'platform-messages-entry',
        title: 'Messages entry',
        entryText: 'Messages are available from the app bar.',
        actionText: 'Open Messages entry from the app bar.',
        resultText: 'Messages entry is reachable.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'platform-connections-entry',
        title: 'Connections entry',
        entryText: 'Connections are available from the app bar.',
        actionText: 'Open Connections entry from the app bar.',
        resultText: 'Connections entry is reachable.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'platform-connection-invite',
        title: 'Connection invite',
        entryText: 'Member can invite an unblocked owner connection.',
        actionText: 'Send connection invite.',
        resultText: 'Connection invite state is invited.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'platform-blocked-target',
        title: 'Blocked-target prevention',
        entryText: 'Blocked target cannot receive a connection invite.',
        actionText: 'Attempt blocked-target invite.',
        resultText: 'Blocked-target invite prevented.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'platform-message-stream',
        title: 'Message stream rendering',
        entryText: 'Community general thread has messages.',
        actionText: 'Render the community message stream.',
        resultText: 'Message stream renders two messages.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'platform-in-stream-ad',
        title: 'In-stream ad disclosure',
        entryText: 'In-stream ad slot can fill with disclosure.',
        actionText: 'Render sponsored in-stream ad item.',
        resultText: 'Sponsored disclosure is visible.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'platform-top-banner-no-fill',
        title: 'Top-banner fill and no-fill',
        entryText: 'Required top banner ad slot is preserved.',
        actionText: 'Evaluate top banner fill and no-fill results.',
        resultText: 'Top banner records required no-fill result.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'platform-sensitive-no-fill',
        title: 'Sensitive-context no-fill',
        entryText: 'Sensitive contexts suppress ad fills.',
        actionText: 'Request ad decision in sensitive context.',
        resultText: 'Sensitive-context ad decision is no-fill.',
      ),
    ],
  ),
  'ext_ad_off': LoomExperienceDefinition(
    extensionId: 'ext_ad_off',
    displayName: 'Ad-Free Community',
    tagline: 'Manage ad-free options, receipts, and member benefits.',
    accentColor: 0xff5b5f97,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'ad-off-member-checkout',
        title: 'Member ad-off checkout',
        entryText: 'Member ad-free checkout is available.',
        actionText: 'Complete member ad-off checkout.',
        resultText: 'Member ad-off entitlement active.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'ad-off-community-checkout',
        title: 'Community ad-off checkout',
        entryText: 'Community-wide ad-free checkout is available.',
        actionText: 'Complete community ad-off checkout.',
        resultText: 'Community ad-off entitlement active.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'ad-off-entitlement-status',
        title: 'Entitlement record',
        entryText: 'Ad-off entitlement can be restored and checked.',
        actionText: 'Verify member and community entitlement record.',
        resultText: 'Entitlement record shows active.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'ad-off-receipt-evidence',
        title: 'Receipt evidence',
        entryText: 'Ad-off purchases link to receipt ledger records.',
        actionText: 'Open ad-off receipt evidence.',
        resultText: 'Ad-off receipt evidence displayed.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'ad-off-ad-suppression',
        title: 'Ad suppression',
        entryText: 'Ad decision changes after entitlement.',
        actionText: 'Evaluate ad decision after ad-off purchase.',
        resultText: 'Ads suppressed by ad-off entitlement.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'ad-off-settlement-utility',
        title: 'Settlement and utility allocation',
        entryText: 'Ad-off economics produce auditable settlement records.',
        actionText: 'Calculate settlement and utility allocation.',
        resultText: 'Settlement and utility allocation recorded.',
      ),
    ],
  ),
  'ext_export_migration': LoomExperienceDefinition(
    extensionId: 'ext_export_migration',
    displayName: 'Data Portability Community',
    tagline: 'Move community data with redaction and transfer checks.',
    accentColor: 0xff536878,
    workflows: [
      LoomWorkflowDefinition(
        workflowId: 'export-import-preview',
        title: 'Import preview',
        entryText: 'Legacy import can be previewed for sensitive fields.',
        actionText: 'Preview legacy CSV import.',
        resultText: 'Import preview reports one sensitive field.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'export-import-replay',
        title: 'Import replay and idempotency',
        entryText: 'Import replay should reuse the committed import result.',
        actionText: 'Replay import with the same idempotency key.',
        resultText: 'Import replay returns the existing import result.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'export-protected-redaction',
        title: 'Protected field routing and redaction',
        entryText: 'Imported phone number routes to protected vault.',
        actionText: 'Open protected field redaction evidence.',
        resultText: 'Protected phone field renders redacted.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'export-schema-listing',
        title: 'Exportable custom-schema listing',
        entryText: 'Custom member note schema is exportable.',
        actionText: 'List exportable extension schemas.',
        resultText: 'custom_member_note appears in exportable schema list.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'export-full-bundle',
        title: 'Full export bundle',
        entryText: 'Full export includes documents and receipts.',
        actionText: 'Create full export bundle.',
        resultText: 'Full export bundle includes document and receipt IDs.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'export-redacted-bundle',
        title: 'Redacted export bundle',
        entryText: 'Redacted export excludes protected raw values.',
        actionText: 'Create redacted export bundle.',
        resultText: 'Redacted export marks protected vault as redacted.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'export-checksum-evidence',
        title: 'Checksum evidence',
        entryText: 'Export bundle should carry checksum evidence.',
        actionText: 'Verify export checksum.',
        resultText: 'Export checksum evidence recorded.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'export-transfer-verification',
        title: 'Provider transfer verification',
        entryText: 'Provider transfer can be verified after export.',
        actionText: 'Verify provider transfer.',
        resultText: 'Provider transfer verified.',
      ),
      LoomWorkflowDefinition(
        workflowId: 'export-transfer-rollback',
        title: 'Provider transfer rollback',
        entryText: 'Failed target checksum can trigger rollback.',
        actionText: 'Rollback provider transfer after checksum mismatch.',
        resultText: 'Provider transfer rolled back.',
      ),
    ],
  ),
};
