// GENERATED — do not edit by hand.
// Source: workflow_capabilities.dart, app_shell_capabilities.dart,
//         and validator_capabilities.dart.
// Regenerate: dart run bin/generate_capability_baseline.dart
library;

const int communityCapabilityBaselineSpecVersion = 4;
const String communityCapabilityBaselineSnapshotDate = '2026-08-20';

const Set<String> communityCapabilityBaseline = <String>{
  'archetype.approvalQueueItem',
  'archetype.calendar',
  'archetype.discussionThread',
  'archetype.documentLibrary',
  'archetype.equipment-loan',
  'archetype.event-rsvp',
  'archetype.exportWizard',
  'archetype.formEntry',
  'archetype.notificationInbox',
  'archetype.paymentCheckout',
  'archetype.searchAiAnswer',
  'archetype.statusTimeline',
  'archetype.table',
  'archetype.votePoll',
  'effect.append',
  'effect.appendUnique',
  'effect.branch',
  'effect.createInstance',
  'effect.decrement',
  'effect.generateRecurringInstances',
  'effect.increment',
  'effect.removeFromTileGrid',
  'effect.removeValue',
  'effect.set',
  'effect.transitionRelated',
  'field.bool',
  'field.date',
  'field.fanId',
  'field.fanId[]',
  'field.image',
  'field.int',
  'field.list',
  'field.map',
  'field.number',
  'field.roleId',
  'field.roleId[]',
  'field.text',
  'field.textarea',
  'field.time',
  'field.url',
  'formula.argMaxKey',
  'formula.avg',
  'formula.combineDateAndTime',
  'formula.contains',
  'formula.count',
  'formula.countDistinct',
  'formula.daysBetween',
  'formula.daysUntil',
  'formula.groupCount',
  'formula.if',
  'formula.indexOf',
  'formula.isAfter',
  'formula.isBefore',
  'formula.isPast',
  'formula.mapGet',
  'formula.max',
  'formula.min',
  'formula.now',
  'formula.size',
  'formula.sortBy',
  'formula.subtractHours',
  'formula.sum',
  'formula.topKeys',
  'guard.actorEqualsField',
  'guard.actorInList',
  'guard.allowedRoleIds',
  'guard.cancellationDeadline',
  'guard.formula',
  'guard.instanceDataEquals',
  'guard.locationOverlap',
  'guard.relatedAggregate',
  'guard.relatedListMembership',
  'guard.requiresWorkflowsComplete',
};
