import 'package:loom_workflow_engine/loom_workflow_engine.dart';

/// Finding codes the community package validator can emit.
///
/// The validator has many independent checks, so retaining one source for all
/// constructors would require a behavior-affecting rewrite. The conformance
/// suite instead extracts the literals from both validator implementations and
/// asserts that this declaration is exact.
const Set<String> communityPackageValidatorFindingCodes = <String>{
  'effect_writable_field_has_no_effect',
  'prefill_written_field_not_platform',
  'document_library_is_link_only',
  'document_upload_stores_no_content',
  'actor_equals_field_on_list_type',
  'ambiguous_workflow_archetype',
  'binding_cap_exceeded',
  'circular_formula_dependency',
  'computed_field_cannot_be_required',
  'computed_field_seeded',
  'computed_field_written_by_effect',
  'context_reference_outside_instance_action',
  'create_action_cannot_set_inputs',
  'dangling_action_transition_id',
  'dangling_action_workflow_type',
  'dangling_actor_equals_field',
  'dangling_allowed_persona_id',
  'dangling_create_instance_target',
  'dangling_filterable_facet_field',
  'dangling_generate_recurring_target',
  'dangling_instance_data_key',
  'dangling_instance_reference',
  'dangling_linked_workflow_id',
  'dangling_recurrence_anchor_field',
  'dangling_recurrence_set_pos_without_weekday',
  'dangling_related_aggregate_filter_field',
  'dangling_related_aggregate_workflow_type',
  'dangling_related_instance_field',
  'dangling_related_list_field',
  'dangling_requires_workflows_complete',
  'dangling_response_table_workflow_type',
  'dangling_source_query_workflow_type',
  'dangling_transition_related_sort_key',
  'dangling_transition_related_transition_id',
  'dangling_transition_related_workflow_type',
  'dangling_visibility_field',
  'dangling_visibility_role',
  'dead_role_binding',
  'dependency_cycle',
  'destructive_transition_ignores_availability_field',
  'duplicate_action_transition_id',
  'duplicate_instance_id',
  'editable_fields_without_edit_guard',
  'effect_field_in_editable_fields',
  'identity_compared_to_role',
  'invalid_formula_syntax',
  'invalid_instance_state',
  'invalid_parties_arity',
  'invalid_recurrence_anchor_field_type',
  'invalid_recurrence_count',
  'invalid_recurrence_freq',
  'invalid_recurrence_interval',
  'invalid_recurrence_month_day',
  'invalid_recurrence_set_pos_value',
  'invalid_recurrence_set_pos_weekday_count',
  'invalid_recurrence_weekday_code',
  'invalid_source_query_syntax',
  'invalid_visibility_field_type',
  'invalid_visibility_principal',
  'invalid_workflow_definition',
  'legacy_identity_key',
  'legacy_identity_type',
  'legacy_version_stamp',
  'missing_action_button_row',
  'missing_experience',
  'missing_instance_id',
  'missing_label',
  'missing_recurrence_anchor_field',
  'missing_recurrence_count',
  'missing_recurrence_freq',
  'missing_recurrence_rule',
  'missing_required_field',
  'missing_schema_version',
  'missing_template',
  'missing_transition_action',
  'missing_visibility_fields',
  'missing_workflow_definitions',
  'no_creation_path_for_editable_type',
  'no_destructive_exit_for_managed_type',
  'no_read_visibility_declared',
  'no_render_binding_for_reachable_state',
  'orphaned_response_rows',
  'possible_fabricated_identifier',
  'recurrence_field_invalid_for_freq',
  'recurrence_month_day_set_pos_conflict',
  'recurrence_weekday_without_set_pos',
  'redundant_transition',
  'seed_instance_missing_creator',
  'sortable_column_without_backing_field',
  'stuck_state',
  'tab_action_cannot_be_button',
  'tab_declares_permission',
  'transition_action_cannot_be_tab_scoped',
  'transition_action_cannot_set_by_persona_ids',
  'transition_action_cannot_set_prefill',
  'transition_action_cannot_set_workflow_type',
  'unexpected_transition_action',
  'unknown_action_input_reference',
  'unknown_action_kind',
  'unknown_action_presentation',
  'unknown_action_scope',
  'unknown_card_surface_family',
  'unknown_effect_op',
  'unknown_formula_field',
  'unknown_formula_function',
  'unknown_input_reference',
  'unknown_input_type',
  'unknown_instance_data_key',
  'unknown_instance_workflow_type',
  'unknown_item_reference',
  'unknown_key',
  'unknown_response_table_field',
  'unknown_response_table_state',
  'unknown_tab_id',
  'unknown_transition_action',
  'unreachable_state',
  'undeclared_capability',
  'unsupported_capability',
  'unsupported_schema_version',
  'unused_capability',
};

/// Families whose semantic action vocabulary is closed and therefore require
/// `transitions[].action` when a bespoke action is used.
///
/// This aliases the resolver registry used by the actual validator checks.
const Set<String> validatorCardSurfaceFamiliesRequiringAction =
    ArchetypeResolver.bespokeFamilies;
